### ISSUE TITLE
It is proposed to transfer this project to the account of Taizhou Luqiao High School

### ISSUE THREAD

**Issue by CodeBoy2006** [Taizhou-Luqiao-Middle-School/vex_code#3]
So, the only thing you should do is to donate this project to our school's ~official~ account.
**An invitation has already been sent to you**; you can click **confirm** to join the school organization.

Thanks for your contribution to our school. Have a nice day!  ❤

**Comment by Chose-B** [comment]
Thanks, I will click it

**Comment by CodeBoy2006** [comment]
Since you have completed the requested operation, please now **delete** the original repository in your account to avoid unnecessary confusion.

Thank you for your cooperation. Choose B.
